# Generated by Django 4.0.5 on 2022-06-24 09:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_gender_alter_linked_scheme_scheme_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='end_user',
            name='gender',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main_app.gender'),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='gender',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main_app.gender'),
        ),
    ]
